version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /adventure
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /gson
    schedule:
      interval: daily
